/// Marques de véhicules — voiture et moto, séparées pour filtrer la
/// suggestion de marque selon le type de véhicule choisi (Constatation →
/// Véhicule). Liste fournie par le métier, importée telle quelle.
class VehicleBrands {
  static const List<String> voiture = [
    'Audi', 'Aixam', 'Alfa Romeo', 'AMC', 'Aston Martin', 'Austin', 'Acura',
    'Alpine', 'ARO', 'Artega', 'Asia', 'Autobianchi', 'AC', 'Aiways',
    'Alpina', 'Addax MTN', 'Alke',
    'BMW', 'Bedford', 'Bentley', 'BMC', 'Buick', 'Brilliance', 'Bugatti',
    'Borgward', 'Bellier', 'BYD', 'Bertone', 'Bee Bee', 'Bollore',
    'BAIC Beijing', 'BAW',
    'Cadillac', 'Casalini', 'Checker', 'Chevrolet', 'Chrysler', 'Citroen',
    'Crosley', 'Changan', 'Carbodies', 'Chery', 'Caterham', 'Cupra',
    'Chatenet',
    'Dacia', 'Daewoo', 'DAF', 'Daihatsu', 'Datsun', 'Dodge',
    'DS Automobiles', 'DFSK', 'Dongfeng', 'Dallara', 'Donkervoort',
    'De Tomaso', 'DR Automobiles', 'Deepal',
    'Excalibur', 'Eagle', 'EVO',
    'Ford', 'Ferrari', 'Fiat', 'Fisker', 'FSO', 'Forthing', 'FSC Żuk',
    'Foton',
    'Galloper', 'GMC', 'Grecav-EKE', 'GAZ', 'Geo', 'Great Wall', 'Genesis',
    'Gem', 'Geely', 'Goupil', 'Gonow',
    'Hanomag', 'Honda', 'Hummer', 'Hyundai', 'Holden', 'Hymer', 'Hongqi',
    'Infiniti', 'Isuzu', 'Iveco', 'Ineos', 'Izh',
    'Jaguar', 'JDM', 'Jeep', 'JAC', 'Jaecoo', 'Jetour',
    'KIA', 'KTM', 'KG Mobility', 'Koenigsegg',
    'Lada', 'Lamborghini', 'Lancia', 'Land Rover', 'Lexus', 'Ligier',
    'Lincoln', 'Lotus', 'LDV', 'Lynk & co', 'Lucid', 'LEVC', 'Landwind',
    'Leapmotor',
    'Mercedes-Benz', 'Maserati', 'Mazda', 'Melex', 'Mercury', 'MG',
    'Microcar', 'Mini', 'Mitsubishi', 'Morris', 'McLaren', 'Moskvich',
    'Man', 'Maxus', 'Mahindra', 'Maybach', 'Morgan', 'Mia', 'MPM Motors',
    'Nissan', 'NSU', 'NIO',
    'Opel', 'Oldsmobile', 'ORA', 'Omoda',
    'Peugeot', 'Piaggio', 'Plymouth', 'Pontiac', 'Porsche', 'Proton',
    'Polestar', 'Perodua', 'Pagani', 'PGO',
    'Renault', 'Rolls-Royce', 'Rover', 'Ram', 'Radical Sportscars',
    'Rivian', 'RAF',
    'Saab', 'Simca', 'Smart', 'SsangYong', 'Subaru', 'Suzuki', 'Seat',
    'Skoda', 'Saturn', 'Scion', 'Santana', 'Seres', 'Sportequipe',
    'StreetScooter', 'Senova',
    'Talbot', 'Toyota', 'Tesla', 'Tata', 'Tazzari', 'Trabant', 'TVR',
    'Think', 'Triumph', 'TYN-e', 'Togg',
    'UAZ',
    'Volvo', 'Volkswagen', 'VAZ', 'Vauxhall', 'Voyah',
    'Wartburg',
    'XPeng',
    'Yamaha',
    'ZAZ', 'Zhidou', 'ZSD', 'Zeekr',
  ];

  static const List<String> moto = [
    'AJP', 'AJS', 'Ace', 'Adler', 'Aeon', 'Aermacchi', 'Agrale', 'Aprilia',
    'ARCH Motorcycle', 'Ariel', 'Arctic Cat', 'Askoll', 'ATK', 'Ather',
    'Auteco',
    'Bajaj', 'Benelli', 'Beta', 'Bianchi', 'Bimota', 'BMW', 'Boss Hoss',
    'Brough Superior', 'BSA', 'Buell', 'Bultaco',
    'Cagiva', 'Can-Am', 'CCM', 'CFMoto', 'Chang Jiang',
    'Cleveland CycleWerks', 'Confederate', 'Curtiss', 'CZ',
    'Daelim', 'Dafra', 'Dayang', 'Dayun', 'Derbi', 'DKW', 'DNA Motors',
    'Dnepr', 'Ducati', 'DYL',
    'Energica', 'Evoke', 'Excelsior',
    'Fantic', 'FB Mondial', 'FAMEL', 'FN', 'FTN Motion',
    'Garelli', 'GasGas', 'Gaokin', 'Ghezzi & Brian', 'Gilera', 'Gogoro',
    'GOVECS', 'GPX',
    'Harley-Davidson', 'Haojin', 'Haojue', 'Havoc', 'Hercules', 'Hero',
    'Honda', 'Horex', 'Husaberg', 'Husqvarna', 'Hyosung',
    'Indian', 'Innocenti', 'Italika', 'Italjet', 'IMZ-Ural', 'IZH',
    'Janus', 'Jawa', 'Jincheng', 'Junak',
    'Kayo', 'Kawasaki', 'Keeway', 'Kinetic', 'Kove', 'KR Motors',
    'Kreidler', 'KTM', 'Kymco',
    'Lambretta', 'Laverda', 'Lifan', 'Lightning Motorcycles', 'LML',
    'Loncin',
    'Maeving', 'Magni', 'Maico', 'Mahindra', 'Malaguti', 'Mash', 'MBK',
    'Meguro', 'Métisse', 'Midual', 'Minsk', 'Modenas', 'Mondial',
    'Montesa', 'Moriwaki', 'Moto Guzzi', 'Moto Morini', 'Moto Rumi',
    'Motobécane', 'Motomel', 'Motobi', 'Motosacoche', 'MotoTrans', 'MTT',
    'Münch', 'Mutt', 'MV Agusta', 'MZ',
    'Naza', 'NIU', 'Nimbus', 'Norton', 'NSU',
    'Ola Electric', 'Ossa',
    'Pannonia', 'Paton', 'Peugeot', 'Peugeot Motocycles', 'PGO', 'Piaggio',
    'Polaris', 'Puch',
    'QJMotor', 'Qingqi', 'Qooder',
    'Rieju', 'Rikuo', 'Rokon', 'Royal Enfield', 'Runner',
    'Sachs', 'Sanglas', 'Saroléa', 'Sazgar', 'Scomadi', 'Scorpa', 'Segway',
    'Senke', 'Sherco', 'SHL', 'Silence', 'Simson', 'Sokół', 'Super Soco',
    'Sur-Ron', 'Suzuki', 'SWM', 'SYM',
    'TGB', 'Terra Modena', 'TM Racing', 'Tohatsu', 'Tomos', 'Triumph',
    'Tunturi', 'TVS', 'TWN',
    'Ultraviolette', 'United', 'Ural', 'US Highland',
    'Velocifero', 'Velomotors', 'Vespa', 'Viar', 'Victory', 'VinFast',
    'Voge', 'Voltz', 'Voxan', 'Vyrus',
    'Walton', 'Wasp', 'WFM', 'WSK',
    'Yamaha', 'Yezdi', 'Yinxiang',
    'Zanella', 'Zero Motorcycles', 'ZiD', 'Znen', 'Zongshen', 'Zontes',
    'Zündapp', 'ZXMOTO',
  ];
}
