@extends('layouts.master')
@section('session')
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet.draw/1.0.4/leaflet.draw.css">
<section class="section"><div class="container-fluid"><div class="title-wrapper pt-30"><h2 class="text-success">{{$pound->exists?'Modifier la fourrière':'Créer une fourrière'}}</h2></div>
@if($errors->any())<div class="alert alert-danger"><ul>@foreach($errors->all() as $error)<li>{{$error}}</li>@endforeach</ul></div>@endif
<form class="card-style" method="POST" action="{{$pound->exists?route('pounds.update',$pound):route('pounds.store')}}">@csrf @if($pound->exists) @method('PUT') @endif
<div class="row g-3"><div class="col-md-6"><label class="form-label">Nom *</label><input class="form-control" name="name" value="{{old('name',$pound->name)}}" required></div><div class="col-md-6"><label class="form-label">Département</label><input class="form-control" name="department" value="{{old('department',$pound->department)}}"></div>
<div class="col-12"><p class="text-muted">Placez le centre puis dessinez précisément la zone de la fourrière. Une marge de pointage de 500 m est appliquée automatiquement sans être dessinée.</p><div id="pound-map" style="height:480px;border-radius:16px"></div></div>
<input type="hidden" name="latitude" id="latitude" value="{{old('latitude',$pound->latitude)}}"><input type="hidden" name="longitude" id="longitude" value="{{old('longitude',$pound->longitude)}}"><input type="hidden" name="geofence" id="geofence" value="{{old('geofence',$pound->geofence?json_encode($pound->geofence):'')}}"><div class="col-12 text-end"><a class="main-btn light-btn" href="{{route('pounds.index')}}">Annuler</a> <button class="main-btn success-btn">Enregistrer</button></div></div></form></div></section>
<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet.draw/1.0.4/leaflet.draw.js"></script><script>document.addEventListener('DOMContentLoaded',()=>{const a=parseFloat(latitude.value)||14.7167,o=parseFloat(longitude.value)||-17.4677,m=L.map('pound-map').setView([a,o],14);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(m);let marker=L.marker([a,o],{draggable:true}).addTo(m),drawn=new L.FeatureGroup().addTo(m),raw=geofence.value;if(raw){try{L.geoJSON(JSON.parse(raw)).eachLayer(l=>drawn.addLayer(l));if(drawn.getLayers().length)m.fitBounds(drawn.getBounds())}catch(e){}}m.addControl(new L.Control.Draw({edit:{featureGroup:drawn},draw:{polyline:false,rectangle:false,circle:false,circlemarker:false,marker:false}}));const pos=p=>{latitude.value=p.lat.toFixed(7);longitude.value=p.lng.toFixed(7)},save=()=>{const l=drawn.getLayers()[0];geofence.value=l?JSON.stringify(l.toGeoJSON().geometry):''};marker.on('dragend',e=>pos(e.target.getLatLng()));m.on('click',e=>{marker.setLatLng(e.latlng);pos(e.latlng)});m.on(L.Draw.Event.CREATED,e=>{drawn.clearLayers();drawn.addLayer(e.layer);save()});m.on(L.Draw.Event.EDITED,save);m.on(L.Draw.Event.DELETED,save)});</script>
@endsection
