@extends('layouts.master')
@section('session')
@php
    $storage = rtrim(config('services.backend.storage_url'), '/').'/';
    $status = ['brouillon'=>['Brouillon','secondary'],'planifiee'=>['Planifiée','primary'],'en_cours'=>['En cours','warning'],'en_reception'=>['En réception','info'],'terminee'=>['Terminée','success'],'annulee'=>['Annulée','danger']][$mission->status] ?? [$mission->status,'secondary'];
    $labels = ['vue_ensemble'=>'Vue d’ensemble','devant'=>'Devant','derriere'=>'Derrière','cote_gauche'=>'Côté gauche','cote_droit'=>'Côté droit','front'=>'Devant','back'=>'Derrière','left'=>'Gauche','right'=>'Droite','sheet'=>'Fiche'];
@endphp
<style>
.mission-hero{background:linear-gradient(135deg,#073b2a,#0b8f55);color:#fff;border-radius:22px;padding:24px;box-shadow:0 16px 38px rgba(7,59,42,.18)}.mission-hero .meta{color:rgba(255,255,255,.78)}
.mission-stat{height:100%;border:1px solid #e7eee9;border-radius:18px;padding:18px;background:#fff}.mission-stat .icon{width:44px;height:44px;border-radius:13px;display:grid;place-items:center;font-size:21px}
.journey-card{border:1px solid #e1eae5;border-radius:18px;background:#fff;transition:.2s;overflow:hidden}.journey-card:hover{transform:translateY(-3px);box-shadow:0 14px 32px rgba(19,61,43,.11);border-color:#a8d9bf}.journey-card button{background:none;border:0;width:100%;text-align:left;padding:18px}
.vehicle-avatar{min-width:52px;width:52px;height:52px;border-radius:16px;background:#e8f7ef;color:#07834e;display:grid;place-items:center;font-size:25px}.step-track{display:flex;gap:7px;flex-wrap:wrap}.step-chip{font-size:12px;font-weight:700;padding:6px 10px;border-radius:20px;background:#f0f3f1;color:#66736c}.step-chip.done{background:#e4f7ec;color:#087844}.step-chip.current{background:#fff2d7;color:#9b6500}
.mission-gallery .carousel-item img{width:100%;height:430px;object-fit:contain;background:#101412;border-radius:14px}.empty-stage{min-height:240px;display:grid;place-items:center;text-align:center;background:#f6f9f7;border-radius:14px;color:#77827c}.nav-pills .nav-link{border-radius:12px;color:#405048}.nav-pills .nav-link.active{background:#07834e}
@media(max-width:767px){.mission-hero{padding:18px}.mission-gallery .carousel-item img{height:280px}}
</style>
<section class="section"><div class="container-fluid pb-5">
<div class="pt-30 mb-4 d-flex flex-wrap align-items-center justify-content-between gap-3"><a href="{{route('missions.index')}}" class="btn btn-outline-secondary">← Retour aux missions</a><a href="{{route('missions.edit',$mission)}}" class="main-btn success-btn">Modifier la mission</a></div>
@if(session('success'))<div class="alert alert-success">{{session('success')}}</div>@endif
<div class="mission-hero mb-4"><div class="row align-items-center g-3"><div class="col-lg-8"><div class="d-flex gap-2 mb-2"><span class="badge bg-light text-dark">{{$mission->type==='programmee'?'PROGRAMMÉE':'DIRECTE'}}</span><span class="badge bg-{{$status[1]}}">{{$status[0]}}</span></div><h2 class="text-white mb-1">{{$mission->code}}</h2><div class="meta">{{$mission->title}} · Créée par {{trim(($mission->creator?->first_name??'').' '.($mission->creator?->last_name??'')) ?: '—'}}</div></div><div class="col-lg-4 text-lg-end"><div class="fs-5 fw-semibold">{{$mission->scheduled_at?->format('d/m/Y à H:i') ?: 'Date non renseignée'}}</div><div class="meta">{{$mission->commune?->nomCommune ?: 'Commune non renseignée'}}</div></div></div></div>
<div class="row g-3 mb-4">
@foreach([['👥','#e8f2ff','#1769aa','Équipe terrain',$mission->agents->count().' agent(s)',$mission->agents->filter(fn($a)=>$a->pivot->checked_in_at)->count().' pointé(s)'],['🚚','#fff2db','#a26700','Transport',$mission->trucks->count().' camion(s)',$mission->provider_name?:'Prestataire non renseigné'],['🏁','#f0eaff','#6847b8','Fourrières prêtes',$readyPounds->count().' site(s)',$readyPounds->join(', ')?:'Aucune'],['🚗','#e7f8f0','#087844','Véhicules',$vehicleJourneys->count().' dossier(s)',$mission->removals->count().' enlèvement(s)']] as $item)
<div class="col-sm-6 col-xl-3"><div class="mission-stat"><div class="icon mb-3" style="background:{{$item[1]}};color:{{$item[2]}}">{{$item[0]}}</div><div class="text-muted small">{{$item[3]}}</div><div class="fw-bold fs-6">{{$item[4]}}</div><small>{{$item[5]}}</small></div></div>@endforeach
</div>
<div class="row g-4 mb-4"><div class="col-lg-7"><div class="card-style h-100"><h4 class="mb-3">Organisation</h4><div class="row g-3"><div class="col-md-6"><div class="text-muted small">Agents affectés</div>@forelse($mission->agents as $agent)<div class="py-2 border-bottom"><strong>{{trim($agent->first_name.' '.$agent->last_name)}}</strong><br><small class="{{$agent->pivot->checked_in_at?'text-success':'text-muted'}}">{{$agent->pivot->checked_in_at?'Pointé le '.date('d/m/Y à H:i',strtotime($agent->pivot->checked_in_at)):'Pas encore pointé'}}</small></div>@empty<p>Ouverte à tous les agents</p>@endforelse</div><div class="col-md-6"><div class="text-muted small">Camions</div>@forelse($mission->trucks as $truck)<div class="py-2 border-bottom"><strong>{{$truck->trailer_brand}} · {{$truck->registration}}</strong><br><small>{{$truck->driver_name ?: 'Chauffeur non renseigné'}} · {{$truck->destination_pound_name ?: 'Destination à préciser'}}</small></div>@empty<p>Aucun camion</p>@endforelse</div></div></div></div>
<div class="col-lg-5"><div class="card-style h-100"><h4 class="mb-3">Réception en fourrière</h4><div class="d-flex gap-3"><div class="vehicle-avatar" style="background:#f0eaff;color:#6847b8">🏢</div><div><strong>{{trim(($mission->receptionAgent?->first_name??'').' '.($mission->receptionAgent?->last_name??'')) ?: 'Agent non renseigné'}}</strong><div>{{$mission->receptionPound?->name ?: 'Poste non renseigné'}}</div><small class="text-muted">Pointage : {{$mission->reception_checked_in_at?->format('d/m/Y à H:i') ?: 'en attente'}}</small><br><small class="text-muted">Fin : {{$mission->completed_at?->format('d/m/Y à H:i') ?: 'en attente'}}</small></div></div></div></div></div>
<div class="d-flex flex-wrap justify-content-between align-items-end gap-2 mb-3"><div><h3 class="mb-1">Parcours des véhicules</h3><p class="text-muted mb-0">Cliquez sur un véhicule pour parcourir Signalement → Enlèvement → Réception.</p></div><span class="badge bg-light text-dark border">{{$vehicleJourneys->count()}} véhicule(s)</span></div>
<div class="row g-3">@forelse($vehicleJourneys as $journey) @php($vehicle=$journey['vehicle']) @php($removal=$journey['removal'])
<div class="col-md-6 col-xl-4"><div class="journey-card h-100"><button type="button" data-bs-toggle="modal" data-bs-target="#journey-{{$journey['key']}}"><div class="d-flex gap-3"><div class="vehicle-avatar">🚘</div><div class="flex-grow-1"><div class="fw-bold fs-6">{{$removal?->vehicle_label ?: trim(($vehicle?->marque??'').' '.($vehicle?->model??'')) ?: 'Véhicule'}}</div><div class="text-muted">{{$removal?->plate ?: $vehicle?->numero_vehicule ?: 'Sans plaque'}}</div><div class="step-track mt-3"><span class="step-chip done">✓ Signalement</span><span class="step-chip {{$removal?'done':'current'}}">{{$removal?'✓':'2'}} Enlèvement</span><span class="step-chip {{$removal?->reception?'done':($removal?'current':'')}}">{{$removal?->reception?'✓':'3'}} Réception</span></div></div><span class="fs-4 text-muted">›</span></div></button></div></div>
@empty<div class="col-12"><div class="card-style text-center text-muted py-5">Aucun véhicule associé à cette mission.</div></div>@endforelse</div>
@foreach($vehicleJourneys as $journey) @php($vehicle=$journey['vehicle']) @php($removal=$journey['removal']) @php($modalId='journey-'.$journey['key'])
<div class="modal fade" id="{{$modalId}}" tabindex="-1"><div class="modal-dialog modal-xl modal-dialog-centered modal-dialog-scrollable"><div class="modal-content border-0 rounded-4"><div class="modal-header"><div><h4 class="modal-title">{{$removal?->vehicle_label ?: trim(($vehicle?->marque??'').' '.($vehicle?->model??'')) ?: 'Véhicule'}}</h4><div class="text-muted">{{$removal?->plate ?: $vehicle?->numero_vehicule ?: 'Sans plaque'}}</div></div><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body">
<ul class="nav nav-pills gap-2 mb-4"><li><button class="nav-link active" data-bs-toggle="pill" data-bs-target="#{{$modalId}}-report">1. Signalement</button></li><li><button class="nav-link" data-bs-toggle="pill" data-bs-target="#{{$modalId}}-removal">2. Enlèvement</button></li><li><button class="nav-link" data-bs-toggle="pill" data-bs-target="#{{$modalId}}-reception">3. Réception</button></li></ul>
<div class="tab-content mission-gallery">
<div class="tab-pane fade show active" id="{{$modalId}}-report">@php($media=$vehicle?->photo??collect()) @include('missions.partials.gallery',['media'=>$media->map(fn($p)=>['url'=>$storage.$p->filepath,'label'=>$labels[$p->position]??'Photo']),'carouselId'=>$modalId.'-report-carousel','empty'=>'Aucune photo de signalement disponible.'])</div>
<div class="tab-pane fade" id="{{$modalId}}-removal">@if(!$removal)<div class="empty-stage"><div><div class="fs-1">⏳</div>Enlèvement pas encore effectué.</div></div>@else<div class="row g-3 mb-3"><div class="col-md-4"><small class="text-muted">Camion</small><div class="fw-bold">{{$removal->truck?->registration?:'—'}}</div></div><div class="col-md-4"><small class="text-muted">Fourrière</small><div class="fw-bold">{{$removal->truck?->destination_pound_name?:'À préciser'}}</div></div><div class="col-md-4"><small class="text-muted">Fiche</small><div class="fw-bold">{{$removal->sheet_photo_path?'Ajoutée':'Non ajoutée'}}</div></div></div>@php($media=$removal->photos->map(fn($p)=>['url'=>$storage.$p->path,'label'=>$labels[$p->angle]??$p->angle])->when($removal->sheet_photo_path,fn($c)=>$c->push(['url'=>$storage.$removal->sheet_photo_path,'label'=>'Fiche']))) @include('missions.partials.gallery',['media'=>$media,'carouselId'=>$modalId.'-removal-carousel','empty'=>'Aucune photo d’enlèvement.']) @endif</div>
<div class="tab-pane fade" id="{{$modalId}}-reception">@if(!$removal?->reception)<div class="empty-stage"><div><div class="fs-1">🏁</div>Réception en attente.</div></div>@else<div class="mb-3"><small class="text-muted">Réceptionné le</small><div class="fw-bold">{{$removal->reception->received_at?->format('d/m/Y à H:i')?:'—'}}</div></div>@php($media=collect(['front','back','left','right','sheet'])->map(fn($a)=>['url'=>data_get($removal->reception,$a.'_photo_path')?$storage.data_get($removal->reception,$a.'_photo_path'):null,'label'=>$labels[$a]])->filter(fn($m)=>$m['url'])) @include('missions.partials.gallery',['media'=>$media,'carouselId'=>$modalId.'-reception-carousel','empty'=>'Aucune photo de réception.']) @endif</div>
</div></div></div></div></div>
@endforeach
</div></section>
@endsection
